### CreateUser
POST http://localhost:8080/user
Content-Type: application/json

{ "nickname":"restCreate0001",
  "firstname":"restUser",
  "lastname":"restUser",
  "gender":"male",
  "pass":"b7d7bd8ad5a68a5b4f1f24b87c12a0f2",
  "status":1
}

> {%
client.global.set("user_id", response.body.id)
 %}

### UpdateUser
PUT http://localhost:8080/user/{{user_id}}
Content-Type: application/json

{ "nickname":"restCreate0009",
  "firstname":"restUser",
  "lastname":"restUser",
  "gender":"male",
  "pass":"b7d7bd8ad5a68a5b4f1f24b87c12a0f2",
  "status":1
}

### GetUser
GET http://localhost:8080/user/{{user_id}}
Accept: application/json

### DeleteUser
DELETE http://localhost:8080/user/{{user_id}}
Accept: application/json


### GetAllUsersNoCursor
GET http://localhost:8080/user?limit=15
Accept: application/json

### GetAllUsers
GET http://localhost:8080/user?limit=100
X-NextCursor: 100
Accept: application/json

> {%
client.global.set("nextCursor", response.headers.valueOf("X-Nextcursor"))
client.global.set("prevCursor", response.headers.valueOf("X-Prevcursor"))
 %}

### GetAllUsersCursorNext
GET http://localhost:8080/user?limit=100
X-NextCursor: {{nextCursor}}
Accept: application/json

> {%
client.global.set("nextCursor", response.headers.valueOf("X-Nextcursor"))
client.global.set("prevCursor", response.headers.valueOf("X-Prevcursor"))
 %}

### GetAllUsersCursorPrev
GET http://localhost:8080/user?limit=100
X-NextCursor: {{prevCursor}}
Accept: application/json

> {%
client.global.set("nextCursor", response.headers.valueOf("X-Nextcursor"))
client.global.set("prevCursor", response.headers.valueOf("X-Prevcursor"))
 %}