builds:
  - main: cmd/redis-cache-example/main.go
    binary: redis-cache
    flags: -tags netgo
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.BuildTime={{.Date}}
      - -X redis/internal/version.Commit={{.FullCommit}}
      - -X redis/internal/version.Version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: amd64
dockers:
  - image_templates:
      - "ghcr.io/hamnsk/redis-cache:{{ .Version }}"
      - "ghcr.io/hamnsk/redis-cache:latest"
    dockerfile: 'Dockerfile'
    build_flag_templates:
      - "--platform=linux/amd64"
archives:
  - name_template: "redis-cache-example-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
checksum:
  name_template: checksums.txt
nfpms:
  - homepage: https://github.com/hamnsk/go_psql_redis_example
    maintainer: s.andrynin@gmail.com
    description: Redis Cache Example
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /opt/rcache
release:
  github:
    owner: hamnsk
    name: go_psql_redis_example
  draft: false
  prerelease: false