{
 "title": "Main APP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Get users Total count by ID",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_cache_example_user_get_duration_seconds_count",
     "legendFormat": "user_id: {{id}}"
    }
   ]
  },
  {
   "title": "Total Request by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "redis_cache_example_user_http_request_duration_seconds_count",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Get User Request Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_cache_example_user_get_request_total"
    }
   ]
  },
  {
   "title": "Get User Request Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_cache_example_user_get_request_success"
    }
   ]
  },
  {
   "title": "Get User Request Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_cache_example_user_get_request_error"
    }
   ]
  },
  {
   "title": "Curent RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_cache_example_user_get_request_total[5m])"
    }
   ]
  },
  {
   "title": "Median Response Time in sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(redis_cache_example_user_http_request_duration_seconds_sum[5m]) / rate(redis_cache_example_user_http_request_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "95% Response Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redis_cache_example_user_http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "95% Get User Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redis_cache_example_user_get_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Responses by Status Code in 5 min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cache_example_user_get_handler_request_total[5m])",
     "legendFormat": "{{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Median Get User Time in sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(redis_cache_example_user_get_duration_seconds_sum[5m]) / rate(redis_cache_example_user_get_duration_seconds_count[5m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "SLO 2.5s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_cache_example_user_http_request_duration_seconds_bucket{le=\"2.5\"}[5m])) by (path)\n/\n  sum(rate(redis_cache_example_user_http_request_duration_seconds_count[5m])) by (path)"
    }
   ]
  },
  {
   "title": "SLO 0,5->2.5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(redis_cache_example_user_http_request_duration_seconds_bucket{le=\"0.5\"}[5m])) by (path)\n+\nsum(rate(redis_cache_example_user_http_request_duration_seconds_bucket{le=\"2.5\"}[5m])) by (path)\n)\n/2/\n  sum(rate(redis_cache_example_user_http_request_duration_seconds_count[5m])) by (path)"
    }
   ]
  }
 ]
}