# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
#    branches: [ "main" ]
    tags:
      - "*"
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Verify dependencies
      run: cd ./app && go mod verify

    - name: Install staticcheck
      run: cd ./app && go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: cd ./app &&  staticcheck ./...
      
    - name: Build
      env:
        CGO_ENABLED: "0"
        GOOS: "linux"
      run: cd ./app && go build -o ./.bin/redis-cache-example -v ./cmd/redis-cache-example/main.go

    - name: Upload Go build results
      uses: actions/upload-artifact@v3
      with:
        name: linux-binary
        path: ./app/.bin/redis-cache-example
        retention-days: 90

