name: Release

on:
  push:
    tags:
      - '*'

jobs:

  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        env:
          CGO_ENABLED: "0"
          GOOS: "linux"
        run: cd ./app && go build -o ./.bin/redis-cache-example -v ./cmd/redis-cache-example/main.go

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./app/.bin/redis-cache-example"
          token: ${{ secrets.GITHUB_TOKEN }}
